* General Settings

** Splash Screen & Starting Scratch

*** Splash Screen

   Inhibiting the default splash screen
   from appearing, and changing the text
   displayed on the scratch file.

   #+begin_src emacs-lisp
     (setq inhibit-startup-screen t)
     (setq initial-major-mode 'text-mode)
     (setq initial-scratch-message 
	   "Present Day, Present Time...\n")
   #+end_src

   
** Basic Additions & Removing Bars
   
*** Removing Bars & Bells

   First we remove unnecessary
   bars that (in my opinion) take 
   screen space that I would rather
   use for other things. Also deactivate
   bells, which are active by default.

   #+begin_src emacs-lisp
   (scroll-bar-mode 0)
   (menu-bar-mode 0)
   (tool-bar-mode 0)
   (setq visible-bell t)
   #+end_src

*** Paths & Loading Files

   Make the default directory the
   windows %HOME% which has to be
   defined by the computer user on
   the windows machine
      
   #+begin_src emacs-lisp
     (setq default-directory (concat (getenv "HOME") "/"))
   #+end_src

*** Screen & Fonts

   I enjoy when the screen starts
   full, since I use it like that
   most of the time.

   #+begin_src emacs-lisp
     (add-to-list 'default-frame-alist 
		  '(fullscreen . fullboth))
   #+end_src

   The font I've been using is the
   /Consolas/ font, not because I have
   any particular affection for it,
   I just happened to find it easy
   to read.

   #+begin_src emacs-lisp
     (set-face-attribute
      'default nil
      :font "Consolas 17" )

     (set-frame-font
      "Consolas 17" nil t)
   #+end_src

*** Time & Battery

    Since I spend so much time inside
    emacs, I do like to see the battery
    and the clock as well

    #+begin_src emacs-lisp
    (display-time-mode 1)
    (display-battery-mode 1)
    #+end_src

*** Key Substitution

**** Killing Buffers

    Defining two different ways of
    deleting buffers, one where we
    can select what buffer to delete
    and the other where we just
    delete the one we are in.
    The custom function was made in
    case I ever feel uncomfortable with
    the way I setup the buffer deletion.

    #+begin_src emacs-lisp
      (defun custom/kill-this-buffer ()
	(interactive) (kill-buffer (current-buffer)))

      (global-set-key (kbd "C-x k")
		      'kill-buffer-and-window)

      (global-set-key (kbd "C-c k")
		      'kill-buffer)

    #+end_src

**** Window resizing

     key bindings for resizing windows!

     #+begin_src emacs-lisp
       (global-set-key (kbd "C-S-<left>") 'shrink-window-horizontally)
       (global-set-key (kbd "C-S-<right>") 'enlarge-window-horizontally)
       (global-set-key (kbd "C-S-<down>") 'shrink-window)
       (global-set-key (kbd "C-S-<up>") 'enlarge-window)
     #+end_src

*** Emacs Encodings

    I must confess I don't understand
    much of the following code, but I
    do think that UTF-8 means good? and
    other thing that is not UTF-8 means
    bad? I dunno.... I just know that
    utf-8 displays all the characters I
    want and need.

    #+begin_src emacs-lisp
      (setq utf-translate-cjk-mode nil)
      (set-language-environment "UTF-8")
      (setq locale-coding-system 'utf-8)
      (set-default-coding-systems 'utf-8)
      (set-terminal-coding-system 'utf-8)
      (set-selection-coding-system
       (if (eq system-type 'windows-nt)
	    'utf-16-le
	  'utf-8))
      (prefer-coding-system 'utf-8)
    #+end_src

*** Backing & File Destiny

    Backing up files on a special
    directory, so that if something
    goes horribly wrong I can still
    have them back.

    #+begin_src emacs-lisp
      (setq backup-by-copying t
	    backup-directory-alist '(("." . "~/.saves/"))
	    delete-old-versions t
	    kept-new-versions 6
	    kept-old-versions 2
	    version-control t)
    #+end_src

*** Styling Of Emacs

    Emacs style I am currently using.
    Might be something quite more
    personalized, or just some random
    thing I found on the Internet.

    #+begin_src emacs-lisp
    (load "~/.emacs.d/elegant-emacs/elegance.el")
    #+end_src


* Packages & Terminals

** Packages & Additions

*** Iscroll
    
    Smooth scrolling for images on files
    and other places.

    #+begin_src emacs-lisp
    (load "~/.emacs.d/lisp/iscroll.el")
    #+end_src

*** Ido
    
    Ido is a better finder for commands
    like 'C-c k' (which in my config is
    the deleting combo), or for 'C-x b'.

    #+begin_src emacs-lisp
      (ido-mode t)
      (setq ido-everywhere t)
      (setq ido-enable-flex-matching t)
    #+end_src
*** Smex
    
    Smex is just like Ido, but
    specific for the 'M-x (...)'
    command.
    
    #+begin_src emacs-lisp
      (global-set-key (kbd "M-x") 'smex)
      (global-set-key (kbd "M-X") 'smex-major-mode-commands)
      (global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)
    #+end_src

*** Which Key Package

    Which Key allows me to know
    the commands available after
    I press any key.

    #+begin_src emacs-lisp
      (use-package which-key
	:ensure t
	:config (which-key-mode))
    #+end_src

*** Pdf Tools

    Package which is still not
    very well integrated with
    windows. But it's possible
    to compile the program and
    use it to read pdf's without
    converting them to an image.

    #+begin_src emacs-lisp
    (pdf-loader-install)
    #+end_src

*** Spell Check

    Spell Check here on Emacs for windows
    is done with an external program called
    'hunspell'. I had to find and get the
    respective binaries, I should get
    hunespell's Portuguese and German dictionaries
    as well.
    
    #+begin_src emacs-lisp
      (setq ispell-program-name
	    "C:/hunspell/bin/hunspell.exe")
      (global-set-key (kbd "C-<f8>")
		      'flyspell-check-previous-highlighted-word)
    #+end_src

*** Auto Complete

    Auto complete tool, very good
    one.

    #+begin_src emacs-lisp
      (use-package auto-complete
	:ensure t
	:init
	(progn
	  (ac-config-default)
	  (global-auto-complete-mode t)))
    #+end_src

*** Company Mode
    #+begin_src emacs-lisp
      ;; Company-mode
      (use-package company
	:ensure t
	:init (add-hook 'after-init-hook 'global-company-mode))
    #+end_src
*** Subtree

    Subtree package for folding and
    unfolding directories in dired
    mode.

    #+begin_src emacs-lisp
      (use-package dired-subtree
	:ensure t
	:bind (:map dired-mode-map
		    ("i" . dired-subtree-insert)
		    (";" . dired-subtree-remove)
		    ("<tab>" . dired-subtree-toggle)
		    ("<backtab>" . dired-subtree-cycle)))
    #+end_src
    
*** Org
    
    All my org related configurations
    go in here. Some packages and some
    interesting things going on.
    
**** Org-bullets

     Org-bullets are only because I do
     find the regular org asterisks a
     bit boring.

     #+begin_src emacs-lisp
       (use-package org-bullets
	 :ensure t
	 :init
	 (setq org-bullets-bullet-list
	       '("◉" "∴" "➞" "➵" "➾"))
	 (setq org-todo-keywords '((sequence "☛ TODO(t)" "|" "✔ DONE(d)" "|")
				   (sequence "∞ WAITING(w)" "|")
				   (sequence "|" "✘ CANCELED(c)")))
	 :config (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
     #+end_src

**** Org Babel

     Allows for very nice source code
     in my notes.

     #+begin_src emacs-lisp
       (org-babel-do-load-languages
	'org-babel-load-languages
	'((sparql . t)
	  (R . t)
	  (python . t)
	  (C . t)
	  (dot . t)
	  (java . t)))
     #+end_src

**** Org Tempo

     specifications of the source code
     block headers

     #+begin_src emacs-lisp
       (require 'org-tempo)
       (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
       (add-to-list 'org-structure-template-alist '("py" . "src python :results output :exports both"))
       (add-to-list 'org-structure-template-alist '("pyp" . "src python :session :results output :exports both"))
       (add-to-list 'org-structure-template-alist '("cp" . "src C"))
       (add-to-list 'org-structure-template-alist '("ja" . "src java :results output"))
       (add-to-list 'org-structure-template-alist '("sp" . "src sparql"))
     #+end_src

**** No Evaluation Prompt

     Removing the evaluation prompt for
     some of the source blocks

     #+begin_src emacs-lisp
       (defun ck/org-confirm-babel-evaluate (lang body)
	 (not (or (string= lang "latex") (string= lang "python"))))
       (setq org-confirm-babel-evaluate 'ck/org-confirm-babel-evaluate)
     #+end_src

**** Set Org Agenda

     Set org agenda related
     settings.

     #+begin_src emacs-lisp
       (setq org-agenda-files (quote ("~/todo.org")))
       (global-set-key (kbd "C-c a") 'org-agenda)
       (customize-set-variable 'org-agenda-files "~/todo.org")
     #+end_src

**** Extra Configurations

     Things I changed probably because 
     did not like that much.

     #+begin_src emacs-lisp
       (setq org-hide-emphasis-markers t)
       (setq org-image-actual-width nil)
       (setq org-ellipsis "⤵")
       (setq org-log-done t)
       (eval-after-load 'org
	 (add-hook 'org-babel-after-execute-hook 'org-redisplay-inline-images))
       (setq org-comfim-babel-evaluate nil)
     #+end_src

*** Dired

    Using Dired+ instead of regular
    dired, with the addition of some
    icons, and some extra things.

    #+begin_src emacs-lisp
      (require 'dired+)
      (use-package treemacs-icons-dired
	:after treemacs dired
	:ensure t
	:config (treemacs-icons-dired-mode))
      (add-hook 'dired-mode-hook 'treemacs-icons-dired-mode)

      (defadvice dired-subtree-toggle (after add-icons activate) (treemacs-icons-dired--display))
      (defadvice dired-subtree-toggle (after add-icons activate) (revert-buffer))
    #+end_src

    Due to some not so pleasing
    colors, I have to define some
    variables to be null.

    #+begin_src emacs-lisp
      (customize-set-variable 'diredp-dir-name t nil)
      (customize-set-variable 'diredp-dir-heading t nil)
      (customize-set-variable 'diredp-file-name t nil)
      (customize-set-variable 'diredp-file-suffix t nil)
    #+end_src

*** Aesthetics

    Just changing some symbols with
    Unicode, for aesthetic reasons.

    #+begin_src emacs-lisp
      (global-prettify-symbols-mode 1)
      (defun add-pretty-lambda ()
	(setq prettify-symbols-alist
	      '(
		("lambda" . 955)
		("delta" . 120517)
		("epsilon" . 120518)
		("->" . 8594)
		("Wking" . 9812)
		("WQueen" . 9813)
		("WRook" . 9814)
		("WBishop" . 9815)
		("WKnight" . 9816)
		("WPawn" . 9817)
		("&Sum" . ∑)
		("<=" . 8804)
		(">=" . 8805)
		("#+BEGIN_SRC"     . "λ")
		("#+END_SRC"       . "λ")
		("#+begin_src"     . "λ")
		("#+end_src"       . "λ")
		)))
      (add-hook 'prog-mode-hook 'add-pretty-lambda)
      (add-hook 'org-mode-hook 'add-pretty-lambda)
    #+end_src

*** Youtube-dl

    Youtube dl is a really good tool
    to get video from the internet into
    my computer. Any sort of video! From
    any site!

    #+begin_src emacs-lisp
      (require 'ytdl)
      (ytdl-add-field-in-download-type-list "Music"
					    "m"
					    (expand-file-name "~/Music")
					    nil)
    #+end_src


** Terminals

*** Eshell Configurations

**** Alias
     
     making find file, and find-
     file-other-window easy to
     use.

     #+begin_src emacs-lisp
     (defalias 'ff 'find-file)
     (defalias 'ffo 'find-file-other-window)
     #+end_src
**** Eshell Prompt

     Making the eshell prompt look
     different.

     #+begin_src emacs-lisp
       (setq 
	eshell-prompt-regexp
	"^[^λ]+ λ ")
       (setq eshell-prompt-function
	     (lambda ()
	       (concat
		(format-time-string
		 "%Y-%m-%d" (current-time))
		(if
		    (= (user-uid) 0) " # " " λ "))))
     #+end_src
     
*** Windows CMD

    eshell doesn't always do everything
    like a terminal it's supposed. there
    are some chars that don't work like
    I was expecting. This can be changed
    but at the same time I might just be
    making a cmd terminal program!

    #+begin_src emacs-lisp
      (defun start-cmd ()
	(interactive)
	(let ((proc (start-process "cmd" nil "cmd.exe" "/C" "start" "\"---\"" "cmd.exe")))
	  (set-process-query-on-exit-flag proc nill)))
    #+end_src



* Programming Languages

** Java

   For Java I am currently making
   use of gradle. I have been learning
   to use the JADE multi-agent systems
   framework.

   #+begin_src emacs-lisp
   (add-hook 'java-mode-hook 'gradle-mode)
   #+end_src

** CLips

   Using the CLisp compiler, 
   gnu compiler for Common lisp.

   #+begin_src emacs-lisp
   (setq inferior-lisp-program "clisp -I")
   #+end_src

** Python

   Well Python has quite a couple
   of things to set up. This is
   basically because in the end
   I am just a python programmer.

*** Elpy
    
    #+begin_src emacs-lisp
      (use-package elpy
	:ensure t
	:init
	(elpy-enable))
    #+end_src

*** Ein

    #+begin_src emacs-lisp
      (use-package ein
	:ensure t
	:init
	:config (require 'ein)
	(require 'ein-notebook))
      (customize-set-variable 'ein:output-area-inlined-images t)
    #+end_src

*** Load Flymake

    #+begin_src emacs-lisp
      (when (load "flymake" t)
	(add-to-list 'flymake-allowed-file-name-masks
		     '("\\.py\\'" flymake-pyflakes-init)))

    #+end_src

*** Pyhton Interpreter

    #+begin_src emacs-lisp
      (setq python-shell-interpreter "python"
	    python-shell-interpreter-args "-i")
    #+end_src

*** Virtual Environments

    #+begin_src emacs-lisp
      (setenv "WORKON_HOME" "c:/Users/afons/py_home")
    #+end_src


** Sparql

   Sparql is quite a very interesting
   thing to play with. The whole Semantic
   web is a very, very interesting thing

   #+begin_src emacs-lisp
     (add-to-list 'auto-mode-alist '("\\.sparql$" . sparql-mode))
     (add-to-list 'auto-mode-alist '("\\.rq$" . sparql-mode))
     (add-hook 'sparql-mode-hook 'auto-complete-mode)
   #+end_src

** Latex

   Might not be a programming language
   but Latex is a very, very good
   formatting language.

   #+begin_src emacs-lisp
     (require 'latex)
     (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
	   TeX-source-correlate-start-server t)
     (add-hook 'TeX-after-compilation-finished-functions
		#'TeX-revert-document-buffer)
     (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.3))
     (put 'dired-find-alternate-file 'disabled nil)
     (add-hook 'text-mode-hook 'flyspell-mode)
   #+end_src

** Haskell

   After being a Python and C programmer
   I would like to become a functional
   programmer. What that means in the
   end is basically to write programs
   in haskell without ever printing nothing
   to the terminal!

   #+begin_src emacs-lisp
   (add-hook 'haskell-mode-hook 'interactive-haskell-mode)
   #+end_src



